### ISSUE TITLE
Precompiled Binaries for newer node versions

### ISSUE THREAD

**Issue by ags131** [nonolith/node-usb#102]
There should be precompiled binaries for Windows on node 4.2.* since its a LTS. Precompiled v5 would be nice too.

**Comment by kurtextrem** [comment]
:+1: node-gyp is just a pain for windows...

**Comment by KyleDavidE** [comment]
:+1:

**Comment by underscorebrody** [comment]
I think there are builds for 4.2.* (v46) now but not 5 (v47) yet
