### ISSUE TITLE
Device not open

### ISSUE THREAD

**Issue by Robertbaelde** [nonolith/node-usb#119]
When i try to load a list of devices, they all return an error saying: "Device is not open". 
What am i doing wrong? 

The code i use: 
```
var usb = require('usb');

$.each(usb.getDeviceList(), function( index, value ) {
	dev = value;
	dev.getStringDescriptor(dev.deviceDescriptor.idProduct, function(error, data){
		console.log(error);
		console.log(data);
	});
});  
```

**Comment by kevinmehall** [comment]
You have to open the device with `dev.open()` before you can call methods that perform IO. Call `dev.close()` when you are done with it.
