### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by wonjun27** [nonolith/node-usb#130]
I'm seeing the following error

when I am running

const usb = require('usb');

Error: Module version mismatch. Expected 48, got 46.

node -v
v4.4.3

npm -v
2.15.1

Is there something to be updated?

I ran 

`npm install --build-from-source
`

as you suggested here https://github.com/nonolith/node-usb/issues/127, but I'm getting the same result. 

Thanks

**Comment by wonjun27** [comment]
npm remove and installing after upgrading node and npm worked.

**Comment by qqnp1100** [comment]
@wonjun27 Same here,
I try every way,but can't solve it .
using in electron
node v6.2.2
electron 1.3.3

log:
`Uncaught Error: Module version mismatch. Expected 49, got 48`

errer code in  ELECTRON_ASAR.js
`return old.apply(this, arguments)`

**Comment by wonjun27** [comment]
@qqnp1100 npm remove and installing after upgrading node and npm worked.
