### ISSUE TITLE
Binding issue on Linux

### ISSUE THREAD

**Issue by dblas** [nonolith/node-usb#37]
Edit: pb on OS X platform is solved. An exception used to throw the main thread before any callback can return anything.
The pb on Linux platform remains (for now).

Hi,
thank you for this module that alleviates many hard things when using dongles.

I, however, encounter some difficulties with it on Linux.
On Linux, it's impossible to create a whole usb object. usb object is created but doesn't have any [[prototype]] property. Impossible to go on in the usb.js script.
The same behaviour occurs with a fully compiled 0.10.24 version under x86_64 and i486.
Any suggestion?

Thanks a lot,
db

**Comment by kevinmehall** [comment]
Since the underlying cause of the original issue here was the global constructors not running, this should have been fixed by f3569c2a8, which removes the dependence on global constructors in favor of explicit initialization calls.

**Comment by mklingles** [comment]
Thank you.  I was able to get past the hang with the new release!
