### ISSUE TITLE
node webkit support ?

### ISSUE THREAD

**Issue by unDemian** [nonolith/node-usb#62]
hi, I tried rebuilding your module using nw-gyp in order it on node webkit? Is there any chance you could add support for node webkit. Thanks

**Comment by kevinmehall** [comment]
What is the error?

I would merge a pull request if there is a simple fix for that build, but I won't have time to test it myself in the near future.

**Comment by ggodlewski** [comment]
I rebuilt it with:

cd node_modules/usb
node-pre-gyp configure --runtime=node-webkit --target=0.12.1
node-pre-gyp build --runtime=node-webkit --target=0.12.1
cd -

seems to work ok
