### ISSUE TITLE
timed out issue

### ISSUE THREAD

**Issue by guizmo51** [nonolith/node-usb#63]
Hi guys, thanks for your great job.
i have an issue with node-sub, I get a time out error. 
I haven't my laptop and I'll add screenshot asap.

I connect to usb device and when I try to send data by using transfer I receive the time out error.
I tried to set the timeout value but nothing happend. Do you have clue or tips about that ?

**Comment by kevinmehall** [comment]
That error normally means the device is not ready to accept that transfer. Why that's the case depends on the specifics of the device. You may need to send a control transfer or use a different endpoint before sending that transfer.
