### ISSUE TITLE
io.js 2.0.0 and 3.0.0 not precompiled

### ISSUE THREAD

**Issue by tcr** [nonolith/node-usb#79]
Check the ABI list here: https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/abi_crosswalk.json

**Comment by kevinmehall** [comment]
io.js 3.0 requires updating nan to 2.0.x and associated changes to the C++.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by kevinmehall** [comment]
Closed in #91 / 1.1.0
