### ISSUE TITLE
How do I get mount point path ?

### ISSUE THREAD

**Issue by richardliu-ami** [nonolith/node-usb#81]
Hi,

I want to use 

```javascript
usb.findByIds(vid, pid)
```
to find out the usb storage path (ex. /mnt/xxx-xxx) but I seem don't see way to do that. Can anyone give me some hint. Thanks.

**Comment by angelmic** [comment]
I modified the node-usb-detection for mac, please check [this](https://github.com/angelmic/node-usb-detection/tree/dev). Only for mac now. Linux later. Windows .. unknow.

**Comment by kevinmehall** [comment]
This library is for communicating with device endpoints directly. It won't help you if you want to use the OS drivers for mass storage and filesystems.

**Comment by richardliu-ami** [comment]
I got it! Thanks!

**Comment by sudhakar3697** [comment]
check [detect-usb](https://www.npmjs.com/package/detect-usb) out. Gives mount path
