### ISSUE TITLE
How to list the devices of the same VID and PID?

### ISSUE THREAD

**Issue by mondalaci** [nonolith/node-usb#85]
Apparently, when multiple devices of the same VID and PID are connected `usb.findByIds()` only returns one of them. How is it possible to list all of them and connect to one of them? Even if this isn't supported by node-usb I'd be interested how to extend it to make this happen.

**Comment by kevinmehall** [comment]
`usb.getDeviceList()` returns all connected devices, which you can filter by `deviceDescriptor` properties. See the [implementation of findByIds](https://github.com/nonolith/node-usb/blob/2f5af73629aa70c169769bdb9d9595b9d869e8ed/usb.js#L19).
