### ISSUE TITLE
Node webkit app error not valid win32 application

### ISSUE THREAD

**Issue by shraddha1112** [nonolith/node-usb#88]
Hello,
I have created a sample application using this module. When I run it as node app it lists all usb. Now when I wrap it with Node-webkit same application is crashing, As per the issue comments I have complied and build the usb module using following command:

node-pre-gyp configure --runtime=node-webkit --target=0.12.3
node-pre-gyp build --runtime=node-webkit --target=0.12.3

But I am getting following error:

"%1 is not a valid Win32 application.
↵D:\Projects\…er\node_modules\usb\src\binding\usb_bindings.node"}

**Comment by changuish** [comment]
maybe you did not rebuild the source.the files you down recently are soure code,only can bu used after build

**Comment by shraddha1112** [comment]
changuish: Thanks that worked!!!

**Comment by jeniaSakirko** [comment]
How do you rebuild the source?

**Comment by shraddha1112** [comment]
Hi, Actually it was long back. Probably its nw-gyp rebuild --target=0.5.0 command.
